version: '3.8'

services:
  database:
    container_name: postgres
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: "kihabbo"
      POSTGRES_USER: "kaiofelps"
      POSTGRES_PASSWORD: "kaio123"
